import smtplib
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class EmailService:
    def __init__(self, sender, password, server="smtp.gmail.com", port=587):
        self.sender = sender
        self.password = password
        self.server = server
        self.port = port
        
    def send_email(self, recipient, subject, body_markdown):
        if not self.sender or not self.password:
            return False, "Email credentials not configured"
            
        try:
            msg = MIMEMultipart('alternative')
            msg['From'] = self.sender
            msg['To'] = recipient
            msg['Subject'] = subject
            
            # Convert Markdown to HTML
            html_content = markdown.markdown(body_markdown)
            
            # Add professional styling
            styled_html = f"""
            <html>
                <head>
                    <style>
                        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                        h1, h2, h3 {{ color: #2c3e50; }}
                        h1 {{ border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
                        h2 {{ margin-top: 25px; }}
                        ul {{ padding-left: 20px; }}
                        li {{ margin-bottom: 5px; }}
                        strong {{ color: #2980b9; }}
                    </style>
                </head>
                <body>
                    {html_content}
                    <br>
                    <hr>
                    <small style="color: #7f8c8d;">Generated by Mira Agent</small>
                </body>
            </html>
            """
            
            # Attach both plain text and HTML versions
            part1 = MIMEText(body_markdown, 'plain')
            part2 = MIMEText(styled_html, 'html')
            
            msg.attach(part1)
            msg.attach(part2)
            
            with smtplib.SMTP(self.server, self.port) as server:
                server.starttls()
                server.login(self.sender, self.password)
                server.send_message(msg)
                
            return True, "Email sent successfully"
        except Exception as e:
            return False, str(e)
